{% set name = "Auto3D" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: abba76886fd930de440eb5894cd30cafd049186bce1977ffee880f172093eab6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pytorch
    - rdkit >=2020.09.01
    - openbabel >=3.1.1
    - pandas
    - pyyaml
    - send2trash
    - tqdm
    - psutil
    - torchani
    - ase

test:
  imports:
    - Auto3D
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/isayevlab/Auto3D_pkg
  summary: Auto3D is a Python package for generating low-energy conformers from SMILES.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LiuCMU
